### ISSUE TITLE
Execute tasks in separated docker container using dedicated image per task

### ISSUE THREAD

**Issue by piotr-kalanski** [piotr-kalanski/service-initializer#11]

**Comment by piotr-kalanski** [comment]
Standard for providing input parameters (Service Metadata) to docker container
- command line
- mount file / volume

**Comment by piotr-kalanski** [comment]
use Docker sdk: https://docker-py.readthedocs.io/en/stable/

**Comment by piotr-kalanski** [comment]
generic way for:
- downloading docker image
- executing docker image

**Comment by piotr-kalanski** [comment]
https://docker-py.readthedocs.io/en/stable/containers.html

```python
import docker

client = docker.from_env()
client.containers.run(
    image='image',
    command='command arguments', 
    auto_remove=True, 
    devices=['<path_on_host>:<path_in_container>:<cgroup_permissions>'], 
    network_mode='host', 
) 
```

**Comment by piotr-kalanski** [comment]
Use os.system(command):

```python
import os
os.system('docker run [...]')
```

**Comment by piotr-kalanski** [comment]
Z pakietem docker jest błąd:
```python
>>> import docker
>>> client = docker.from_env()
Traceback (most recent call last):
  File "C:\Users\kalanp01\IdeaProjects\service-initializer\env\lib\site-packages\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kalanp01\IdeaProjects\service-initializer\env\lib\site-packages\docker\client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "C:\Users\kalanp01\IdeaProjects\service-initializer\env\lib\site-packages\docker\client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "C:\Users\kalanp01\IdeaProjects\service-initializer\env\lib\site-packages\docker\api\client.py", line 159, in __init__
    'Install pypiwin32 package to enable npipe:// support'
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
```
